<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.richie696.component</groupId>
        <artifactId>atlas-richie-component-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../atlas-richie-component-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>atlas-richie-mcp-parent</artifactId>
    <name>atlas-richie-mcp-parent</name>
    <packaging>pom</packaging>

    <modules>
        <module>atlas-richie-mcp-api</module>
        <module>atlas-richie-mcp-protocol</module>
        <module>atlas-richie-mcp-schema</module>
        <module>atlas-richie-mcp-server-core</module>
        <module>atlas-richie-mcp-transport-http</module>
        <module>atlas-richie-mcp-transport-stdio</module>
        <module>atlas-richie-mcp-security-oauth</module>
        <module>atlas-richie-mcp-server-spring-boot-starter</module>
        <module>atlas-richie-mcp-client-spring-boot-starter</module>
        <module>atlas-richie-mcp-testkit</module>
    </modules>
</project>
