server:
    port: 8081

spring:
    application:
        name: sample-storage-minio
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

# Minio存储配置
platform:
    component:
        storage:
            object:
                # 存储引擎类型
                engine: MINIO
                # Minio访问地址
                endpoint: http://localhost:9000
                # 区域（可选）
                region: us-east-1
                # 访问密钥ID
                access-key-id: minioadmin
                # 访问密钥
                access-key-secret: minioadmin
                # 存储桶名称
                bucket-name: richie-bucket
                # 桶内基础路径（可选）
                base-path: /storage

logging:
    level:
        com.richie: DEBUG
