# Elasticsearch ??????
# Spring Data Elasticsearch ???
logging.level.org.springframework.data.elasticsearch=DEBUG
logging.level.org.springframework.data.elasticsearch.core=DEBUG
logging.level.org.springframework.data.elasticsearch.client=DEBUG

# Elasticsearch ?????
logging.level.co.elastic.clients=DEBUG
logging.level.co.elastic.clients.elasticsearch=DEBUG
logging.level.co.elastic.clients.transport=DEBUG

# HTTP ?????????? HTTP ??????
logging.level.org.apache.http=DEBUG
logging.level.org.apache.http.wire=DEBUG

# ?????
logging.level.root=INFO
