package com.richie.component.cache.redis.bean;

/**
 * Redis Stream 记录ID
 *
 * <p>封装消息ID的原始值与拆分出的 sequence/timestamp 字段，以及是否自动生成。
 *
 * @param value 原始ID字符串
 * @param sequence 序列号部分
 * @param timestamp 时间戳部分
 * @param shouldBeAutoGenerated 是否应该由 Redis 自动生成
 */
public record RecordId(
        String value,
        Long sequence,
        Long timestamp,
        boolean shouldBeAutoGenerated
) {}
