<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.richie696.component</groupId>
        <artifactId>atlas-richie-component-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../atlas-richie-component-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>atlas-richie-component-vector</artifactId>
    <name>atlas-richie-component-vector-parent</name>
    <description>Richie向量数据库父模块（聚合core及各provider实现）</description>
    <packaging>pom</packaging>

    <modules>
        <module>vector-core</module>
        <module>vector-chunk-adapter</module>
        <module>vector-projection-dao</module>
        <module>vector-mongodb-atlas</module>
        <module>vector-neo4j</module>
        <module>vector-postgresql</module>
        <module>vector-qdrant</module>
        <module>vector-redis</module>
        <module>vector-weaviate</module>
        <module>vector-milvus</module>
        <module>vector-vikingdb</module>
    </modules>

</project>
