package cn.richie696.component.secret.provider.kmip;

import cn.richie696.component.secret.api.*; import cn.richie696.component.secret.api.crypto.*; import cn.richie696.component.secret.api.exception.*; import cn.richie696.component.secret.api.provider.*; import cn.richie696.component.secret.bootstrap.BootstrapSecretProperties; import cn.richie696.component.secret.bootstrap.spi.*;
import org.springframework.boot.context.properties.bind.Binder; import org.springframework.core.env.ConfigurableEnvironment;
import javax.net.ssl.*; import java.io.*; import java.net.*; import java.nio.ByteBuffer; import java.nio.ByteOrder; import java.nio.file.Files; import java.nio.file.Path; import java.security.KeyStore; import java.util.*; import java.util.concurrent.atomic.AtomicBoolean;

/** KMIP 2.1 TLS session. Only protocol Encrypt/Decrypt is exposed as wrap/unwrap. */
public final class KmipSecretClient implements SecretBootstrapClient, KeyWrappingBackend, SecretProviderSession {
    private static final int REQUEST_MESSAGE=0x420078, REQUEST_HEADER=0x420077, PROTOCOL_VERSION=0x420069, MAJOR=0x42006a, MINOR=0x42006b, BATCH_COUNT=0x42000d, BATCH_ITEM=0x42000f, OPERATION=0x42005c, REQUEST_PAYLOAD=0x420079, UNIQUE_IDENTIFIER=0x420094, DATA=0x4200c2, CRYPTO_PARAMETERS=0x42002b, CRYPTO_ALGORITHM=0x420028, BLOCK_CIPHER_MODE=0x420011, RESPONSE_DATA=0x4200c2;
    private static final Set<SecretCapability> CAPABILITIES=Set.of(SecretCapability.KEY_WRAP,SecretCapability.KEY_UNWRAP);
    private final String providerId, hash; private final KmipSecretProperties properties; private final BootstrapSecretProperties bootstrap; private final SSLSocketFactory socketFactory; private final AtomicBoolean closed=new AtomicBoolean();
    private KmipSecretClient(String id,String hash,KmipSecretProperties p,BootstrapSecretProperties b,SSLSocketFactory socketFactory){providerId=id;this.hash=hash;properties=p;bootstrap=b;this.socketFactory=socketFactory;}
    static KmipSecretClient create(ConfigurableEnvironment env,BootstrapSecretProperties b){String prefix=KmipSecretProperties.PREFIX,id="kmip";String active=b.getActiveProvider();if(active!=null&&!active.isBlank()&&b.getProviders().containsKey(active)){prefix=BootstrapSecretProperties.PREFIX+".providers."+active;id=active;}KmipSecretProperties p=Binder.get(env).bind(prefix,KmipSecretProperties.class).orElseGet(KmipSecretProperties::new);KmipSecretConfiguration.validate(p);try{return new KmipSecretClient(id,KmipSecretConfiguration.hash(id,p),p,b,sslSocketFactory(p));}catch(SecretException e){throw e;}catch(Exception e){throw new SecretConfigurationException("SEC-BOOT-003","KMIP TLS context cannot be created",e);}}
    @Override public SecretBootstrapResult load(SecretBootstrapRequest request){ensure();return new SecretBootstrapResult(providerId,"kms-only",String.join(",",request.logicalPaths()),java.time.Instant.now(),Map.of(),null);}
    @Override public WrappedKey wrap(KeyReference ref,byte[] plaintext,CryptoContext context){ensure();if(plaintext==null||plaintext.length==0)throw new SecretCryptoException("SEC-CRYPTO-001","Plaintext data key must not be empty");if(context!=null&&context.associatedData().length>0)throw new SecretCryptoException("SEC-CRYPTO-003","KMIP AES Key Wrap does not support AAD");byte[] result=operation(31,ref,plaintext);return new WrappedKey(result,"kmip-aes-kwp");}
    @Override public byte[] unwrap(KeyReference ref,WrappedKey wrapped,CryptoContext context){ensure();if(!"kmip-aes-kwp".equals(wrapped.algorithm()))throw new SecretCryptoException("SEC-CRYPTO-002","Wrapped key algorithm is not supported by KMIP");byte[] data=wrapped.value();try{return operation(32,ref,data);}finally{Arrays.fill(data,(byte)0);}}
    @Override public SecretProviderDescriptor descriptor(){return new SecretProviderDescriptor("kmip",providerId,CAPABILITIES);} @Override public Optional<SecretBackend> secretBackend(){return Optional.empty();} @Override public Optional<KeyWrappingBackend> keyWrappingBackend(){return Optional.of(this);} String configurationHash(){return hash;} @Override public void close(){closed.set(true);}
    private byte[] operation(int op,KeyReference ref,byte[] data){try{byte[] body=KmipTtlv.structure(REQUEST_MESSAGE,KmipTtlv.structure(REQUEST_HEADER,KmipTtlv.structure(PROTOCOL_VERSION,KmipTtlv.integer(MAJOR,properties.getProtocolMajor()),KmipTtlv.integer(MINOR,properties.getProtocolMinor())),KmipTtlv.integer(BATCH_COUNT,1)),KmipTtlv.structure(BATCH_ITEM,KmipTtlv.enumeration(OPERATION,op),KmipTtlv.structure(REQUEST_PAYLOAD,KmipTtlv.text(UNIQUE_IDENTIFIER,key(ref)),KmipTtlv.structure(CRYPTO_PARAMETERS,KmipTtlv.enumeration(BLOCK_CIPHER_MODE,12),KmipTtlv.enumeration(CRYPTO_ALGORITHM,3)),KmipTtlv.bytes(DATA,data))));byte[] response=send(body);byte[] result=KmipTtlv.first(KmipTtlv.children(response),RESPONSE_DATA,KmipTtlv.BYTE_STRING);if(result==null)throw new SecretCryptoException("SEC-CRYPTO-001","KMIP response did not contain Data");return result;}catch(SecretException e){throw e;}catch(Exception e){throw new SecretCryptoException("SEC-CRYPTO-001","KMIP operation failed",e);}}
    private byte[] send(byte[] request)throws Exception{URI e=properties.getEndpoint();int port=e.getPort()>0?e.getPort():5696;SSLSocket socket=(SSLSocket)socketFactory.createSocket(e.getHost(),port);socket.setSoTimeout((int)bootstrap.getResilience().getReadTimeout().toMillis());try{socket.startHandshake();OutputStream out=socket.getOutputStream();out.write(request);out.flush();InputStream input=socket.getInputStream();byte[] header=readFully(input,8);int length=java.nio.ByteBuffer.wrap(header,4,4).getInt();if(length<0||length>16*1024*1024)throw new IOException("KMIP response length is invalid");int padded=length+((8-(length%8))%8);byte[] body=readFully(input,padded);ByteArrayOutputStream received=new ByteArrayOutputStream(8+padded);received.write(header);received.write(body);return received.toByteArray();}finally{socket.close();}}
    private static byte[] readFully(InputStream input,int length)throws IOException{byte[] result=new byte[length];int offset=0;while(offset<length){int n=input.read(result,offset,length-offset);if(n<0)throw new EOFException("KMIP response ended before the TTLV value was complete");offset+=n;}return result;}
    private static SSLSocketFactory sslSocketFactory(KmipSecretProperties p)throws Exception{TrustManager[] trust=null;KeyManager[] keys=null;if(p.getTrustStore()!=null&&!p.getTrustStore().isBlank()){KeyStore store=KeyStore.getInstance(KeyStore.getDefaultType());char[] password=p.getTrustStorePassword();try(var input=Files.newInputStream(Path.of(p.getTrustStore()))){store.load(input,password);}finally{Arrays.fill(password,'\0');}TrustManagerFactory factory=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());factory.init(store);trust=factory.getTrustManagers();}if(p.getKeyStore()!=null&&!p.getKeyStore().isBlank()){KeyStore store=KeyStore.getInstance(KeyStore.getDefaultType());char[] password=p.getKeyStorePassword();try(var input=Files.newInputStream(Path.of(p.getKeyStore()))){store.load(input,password);KeyManagerFactory factory=KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());factory.init(store,password);keys=factory.getKeyManagers();}finally{Arrays.fill(password,'\0');}}SSLContext context=SSLContext.getInstance("TLS");context.init(keys,trust,null);return context.getSocketFactory();}
    private String key(KeyReference ref){return properties.getKeyBindings().getOrDefault(ref.logicalKey(),ref.logicalKey());} private void ensure(){if(closed.get())throw new IllegalStateException("KMIP Secret Provider is closed");}
}
