#
# /*
#  * Copyright (c) 2026 Richie (https://www.github.com/richie696)
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */
#

# OpenFeign OkHttp 默认配置
spring:
    cloud:
        openfeign:
            okhttp:
                enabled: true
            httpclient:
                # 连接池配置
                max-connections: 200
                max-connections-per-route: 50
                time-to-live: 5
                time-to-live-unit: minutes

                # Okhttp客户端配置
                ok-http:
                    # 超时配置（生产环境推荐值）
                    read-timeout: 20s
                    connect-timeout: 8s
                    write-timeout: 15s
                    call-timeout: 50

                    # 日志配置（开发环境可以考虑用BODY，生产使用BASIC，否则日志会爆炸）
                    level: basic

                    # 缓存配置（生产环境默认关闭）
                    enable-cache: false
                    cache-path: /tmp/okhttp3/cache/
                    cache-size: 100

                    # 安全配置（生产环境安全设置）
                    insecure-trust-all: false
                    hostname-verification: true
