<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.richie696.component</groupId>
        <artifactId>atlas-richie-component-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../atlas-richie-component-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>atlas-richie-document-chunking-parent</artifactId>
    <name>atlas-richie-document-chunking-parent</name>
    <packaging>pom</packaging>

    <modules>
        <module>atlas-richie-document-chunking-core</module>
        <module>atlas-richie-document-chunking-parser-adapter</module>
        <module>atlas-richie-document-chunking-semantic-spring-ai</module>
    </modules>
</project>
