#
# /*
#  * Copyright (c) 2026 Richie (https://www.github.com/richie696)
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */
#

platform:
  component:
    vector:
      provider: weaviate
      weaviate:
        scheme: http
        host: localhost:8080
        apiKey: your-api-key         # Weaviate API Key（无需认证时可留空）
        objectClass: MyVectorClass   # Weaviate中用于存储向量的Class名称
        consistencyLevel: QUORUM    # 一致性级别，可选ONE/QUORUM/ALL
        filterMetadataFields: country:text,year:number # 可过滤的元数据字段及类型 