package cn.richie696.component.secret.provider.pkcs11;

import cn.richie696.component.secret.api.*; import cn.richie696.component.secret.api.crypto.*; import cn.richie696.component.secret.api.exception.*; import cn.richie696.component.secret.api.provider.*; import cn.richie696.component.secret.bootstrap.BootstrapSecretProperties; import cn.richie696.component.secret.bootstrap.spi.*;
import org.springframework.boot.context.properties.bind.Binder; import org.springframework.core.env.ConfigurableEnvironment;
import javax.crypto.Cipher; import javax.crypto.SecretKey; import javax.crypto.spec.SecretKeySpec; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.security.*; import java.util.*; import java.util.concurrent.atomic.AtomicBoolean;

/** PKCS#11 client backed by the JDK SunPKCS11 provider; no key material is persisted. */
public final class Pkcs11SecretClient implements SecretBootstrapClient, KeyWrappingBackend, SigningBackend, SecretProviderSession {
    private static final Set<SecretCapability> CAPABILITIES=Set.of(SecretCapability.KEY_WRAP,SecretCapability.KEY_UNWRAP,SecretCapability.SIGN,SecretCapability.VERIFY); private final String providerId,hash; private final Pkcs11SecretProperties properties; private final KeyStore keyStore; private final Provider provider; private final char[] pin; private final Map<String,Key> keyCache=new HashMap<>(); private final Map<String,java.security.cert.Certificate> certificateCache=new HashMap<>(); private final AtomicBoolean closed=new AtomicBoolean();
    private Pkcs11SecretClient(String id,String hash,Pkcs11SecretProperties p,KeyStore ks,Provider provider,char[] pin){providerId=id;this.hash=hash;properties=p;keyStore=ks;this.provider=provider;this.pin=pin;for(String alias:p.getKeyBindings().values()){try{Key key=ks.getKey(alias,pin);if(key!=null)keyCache.put(alias,key);java.security.cert.Certificate certificate=ks.getCertificate(alias);if(certificate!=null)certificateCache.put(alias,certificate);}catch(Exception ignored){/* operation-level errors retain the normal provider error mapping */}}}
    static Pkcs11SecretClient create(ConfigurableEnvironment env,BootstrapSecretProperties b){String prefix=Pkcs11SecretProperties.PREFIX,id="pkcs11";String active=b.getActiveProvider();if(active!=null&&!active.isBlank()&&b.getProviders().containsKey(active)){prefix=BootstrapSecretProperties.PREFIX+".providers."+active;id=active;}Pkcs11SecretProperties p=Binder.get(env).bind(prefix,Pkcs11SecretProperties.class).orElseGet(Pkcs11SecretProperties::new);Pkcs11SecretConfiguration.validate(p);try{Provider base=Security.getProvider("SunPKCS11");if(base==null)throw new SecretConfigurationException("SEC-BOOT-003","JDK SunPKCS11 provider is unavailable");Path config=Files.createTempFile("atlas-secret-pkcs11-",".cfg");StringBuilder text=new StringBuilder("name=AtlasSecret");text.append("\nlibrary=").append(p.getLibrary());if(p.getSlot()!=null)text.append("\nslot=").append(p.getSlot());text.append("\nexplicitCancel=true");/* SunPKCS11 does not support a tokenLabel configuration keyword; slot is the portable selector. */Files.writeString(config,text.toString(),StandardCharsets.UTF_8,StandardOpenOption.TRUNCATE_EXISTING);Provider configured;try{configured=base.configure(config.toString());}finally{Files.deleteIfExists(config);}if(Security.addProvider(configured)<0){Provider installed=Security.getProvider(configured.getName());if(installed!=null)configured=installed;}char[] pin=p.getPin();KeyStore ks=KeyStore.getInstance("PKCS11",configured);ks.load(null,pin);return new Pkcs11SecretClient(id,Pkcs11SecretConfiguration.hash(id,p),p,ks,configured,pin);}catch(SecretException e){throw e;}catch(Exception e){throw new SecretConfigurationException("SEC-BOOT-003","PKCS#11 token cannot be opened",e);}}
    @Override public SecretBootstrapResult load(SecretBootstrapRequest request){ensure();return new SecretBootstrapResult(providerId,"kms-only",String.join(",",request.logicalPaths()),java.time.Instant.now(),Map.of(),null);}
    @Override public WrappedKey wrap(KeyReference ref,byte[] plaintext,CryptoContext context){ensure();if(plaintext==null||plaintext.length==0)throw new SecretCryptoException("SEC-CRYPTO-001","Plaintext data key must not be empty");try{Cipher cipher=cipher(Cipher.WRAP_MODE,ref);return new WrappedKey(cipher.wrap(new SecretKeySpec(plaintext,"AES")),"pkcs11-aes-wrap");}catch(GeneralSecurityException unsupported){try{return new WrappedKey(rfc3394Wrap(secretKey(ref),plaintext),"pkcs11-aes-wrap");}catch(Exception e){throw new SecretCryptoException("SEC-CRYPTO-001","PKCS#11 wrap operation failed",e);}}catch(Exception e){throw new SecretCryptoException("SEC-CRYPTO-001","PKCS#11 wrap operation failed",e);}}
    @Override public byte[] unwrap(KeyReference ref,WrappedKey wrapped,CryptoContext context){ensure();if(!"pkcs11-aes-wrap".equals(wrapped.algorithm()))throw new SecretCryptoException("SEC-CRYPTO-002","Wrapped key algorithm is not supported by PKCS#11");byte[] value=wrapped.value();try{Cipher cipher=cipher(Cipher.UNWRAP_MODE,ref);Key key=cipher.unwrap(value,"AES",Cipher.SECRET_KEY);byte[] encoded=key.getEncoded();if(encoded==null)throw new SecretCryptoException("SEC-CRYPTO-002","PKCS#11 returned a non-extractable unwrapped key");return encoded;}catch(GeneralSecurityException unsupported){try{return rfc3394Unwrap(secretKey(ref),value);}catch(Exception e){throw new SecretCryptoException("SEC-CRYPTO-002","PKCS#11 unwrap operation failed",e);}}catch(SecretException e){throw e;}catch(Exception e){throw new SecretCryptoException("SEC-CRYPTO-002","PKCS#11 unwrap operation failed",e);}finally{Arrays.fill(value,(byte)0);}}
    @Override public SignatureValue sign(KeyReference ref,byte[] payload,CryptoContext context){ensure();validateSigningKey(ref);if(payload==null||payload.length==0)throw new SecretCryptoException("SEC-SIGN-001","Signing payload must not be empty");try{Signature signature=Signature.getInstance(properties.getSigningAlgorithm(),provider);signature.initSign(privateKey(ref));signature.update(payload);return new SignatureValue("pkcs11:v1:"+properties.getSigningAlgorithm()+":"+Base64.getEncoder().encodeToString(signature.sign()));}catch(SecretException e){throw e;}catch(Exception e){throw new SecretCryptoException("SEC-SIGN-001","PKCS#11 signing operation failed",e);}}
    @Override public boolean verify(KeyReference ref,byte[] payload,SignatureValue value,CryptoContext context){ensure();validateSigningKey(ref);if(payload==null||payload.length==0||value==null)throw new SecretCryptoException("SEC-SIGN-002","Verification input must not be empty");try{String[] parts=value.value().split(":",4);if(parts.length!=4||!"pkcs11".equals(parts[0])||!"v1".equals(parts[1])||!properties.getSigningAlgorithm().equals(parts[2]))throw new SecretCryptoException("SEC-SIGN-002","PKCS#11 signature value is malformed");Signature signature=Signature.getInstance(parts[2],provider);signature.initVerify(publicKey(ref));signature.update(payload);return signature.verify(Base64.getDecoder().decode(parts[3]));}catch(SecretException e){throw e;}catch(Exception e){throw new SecretCryptoException("SEC-SIGN-002","PKCS#11 verification operation failed",e);}}
    @Override public SecretProviderDescriptor descriptor(){return new SecretProviderDescriptor("pkcs11",providerId,CAPABILITIES);} @Override public Optional<SecretBackend> secretBackend(){return Optional.empty();} @Override public Optional<KeyWrappingBackend> keyWrappingBackend(){return Optional.of(this);} @Override public Optional<SigningBackend> signingBackend(){return Optional.of(this);} String configurationHash(){return hash;} @Override public void close(){if(closed.compareAndSet(false,true))Arrays.fill(pin,'\0');}
    private Cipher cipher(int mode,KeyReference ref)throws Exception{SecretKey secret=secretKey(ref);try{return init("AESWrap",mode,secret);}catch(GeneralSecurityException first){return init("AES/KW/NoPadding",mode,secret);}}
    private SecretKey secretKey(KeyReference ref)throws Exception{String alias=properties.getKeyBindings().getOrDefault(ref.logicalKey(),ref.logicalKey());Key key=key(alias);if(!(key instanceof SecretKey secret))throw new SecretCryptoException("SEC-CRYPTO-001","PKCS#11 alias is not a secret key: "+alias);return secret;}
    private byte[] rfc3394Wrap(SecretKey key,byte[] plaintext)throws Exception{if(plaintext.length<16||plaintext.length%8!=0)throw new SecretCryptoException("SEC-CRYPTO-001","AES key wrap requires a 16/24/32-byte plaintext");int n=plaintext.length/8;byte[] a=Arrays.copyOf(new byte[]{(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6},8);byte[][] r=new byte[n+1][];for(int i=1;i<=n;i++)r[i]=Arrays.copyOfRange(plaintext,(i-1)*8,i*8);Cipher aes=Cipher.getInstance("AES/ECB/NoPadding",provider);aes.init(Cipher.ENCRYPT_MODE,key);for(int j=0;j<6;j++)for(int i=1;i<=n;i++){byte[] block=new byte[16];System.arraycopy(a,0,block,0,8);System.arraycopy(r[i],0,block,8,8);byte[] encrypted=aes.update(block);System.arraycopy(encrypted,0,a,0,8);xorCounter(a,j*n+i);System.arraycopy(encrypted,8,r[i],0,8);Arrays.fill(block,(byte)0);Arrays.fill(encrypted,(byte)0);}Arrays.fill(aes.doFinal(),(byte)0);byte[] result=new byte[(n+1)*8];System.arraycopy(a,0,result,0,8);for(int i=1;i<=n;i++)System.arraycopy(r[i],0,result,i*8,8);return result;}
    private byte[] rfc3394Unwrap(SecretKey key,byte[] wrapped)throws Exception{if(wrapped.length<24||wrapped.length%8!=0)throw new SecretCryptoException("SEC-CRYPTO-002","AES key unwrap requires a valid RFC 3394 value");int n=wrapped.length/8-1;byte[] a=Arrays.copyOfRange(wrapped,0,8);byte[][] r=new byte[n+1][];for(int i=1;i<=n;i++)r[i]=Arrays.copyOfRange(wrapped,i*8,(i+1)*8);Cipher aes=Cipher.getInstance("AES/ECB/NoPadding",provider);aes.init(Cipher.DECRYPT_MODE,key);for(int j=5;j>=0;j--)for(int i=n;i>=1;i--){byte[] block=new byte[16];System.arraycopy(a,0,block,0,8);xorCounter(block,j*n+i);System.arraycopy(r[i],0,block,8,8);byte[] decrypted=aes.update(block);System.arraycopy(decrypted,0,a,0,8);System.arraycopy(decrypted,8,r[i],0,8);Arrays.fill(block,(byte)0);Arrays.fill(decrypted,(byte)0);}Arrays.fill(aes.doFinal(),(byte)0);if(!MessageDigest.isEqual(a,new byte[]{(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6,(byte)0xA6}))throw new SecretCryptoException("SEC-CRYPTO-002","PKCS#11 wrapped key integrity check failed");byte[] result=new byte[n*8];for(int i=1;i<=n;i++)System.arraycopy(r[i],0,result,(i-1)*8,8);return result;}
    private static void xorCounter(byte[] value,int counter){value[7]^=(byte)counter;value[6]^=(byte)(counter>>>8);value[5]^=(byte)(counter>>>16);value[4]^=(byte)(counter>>>24);}
    private Key key(String alias)throws Exception{Key cached=keyCache.get(alias);if(cached!=null)return cached;Key loaded=keyStore.getKey(alias,pin);if(loaded!=null)keyCache.put(alias,loaded);return loaded;}
    private PrivateKey privateKey(KeyReference ref)throws Exception{String alias=properties.getKeyBindings().getOrDefault(ref.logicalKey(),ref.logicalKey());Key key=key(alias);if(!(key instanceof PrivateKey privateKey))throw new SecretCryptoException("SEC-SIGN-001","PKCS#11 alias is not a private key: "+alias);return privateKey;}
    private PublicKey publicKey(KeyReference ref)throws Exception{String alias=properties.getKeyBindings().getOrDefault(ref.logicalKey(),ref.logicalKey());java.security.cert.Certificate certificate=certificateCache.get(alias);if(certificate==null){certificate=keyStore.getCertificate(alias);if(certificate!=null)certificateCache.put(alias,certificate);}if(certificate==null||certificate.getPublicKey()==null)throw new SecretCryptoException("SEC-SIGN-002","PKCS#11 certificate is missing for alias: "+alias);return certificate.getPublicKey();}
    private void validateSigningKey(KeyReference ref){if(ref==null||ref.purpose()!=KeyPurpose.SIGNING)throw new SecretConfigurationException("SEC-KEY-003","Signing requires a KeyReference with SIGNING purpose");}
    private Cipher init(String algorithm,int mode,SecretKey key)throws Exception{Cipher cipher=Cipher.getInstance(algorithm,provider);cipher.init(mode,key);return cipher;} private void ensure(){if(closed.get())throw new IllegalStateException("PKCS#11 Secret Provider is closed");}
}
