<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.richie696.component</groupId>
        <artifactId>atlas-richie-component-vector</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>vector-projection-dao</artifactId>
    <name>vector-projection-dao</name>
    <description>向量投影版本、manifest 与延迟清理 DAO 插件</description>
    <dependencies>
        <dependency>
            <groupId>cn.richie696.component</groupId>
            <artifactId>vector-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.richie696.component</groupId>
            <artifactId>atlas-richie-component-dao</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
