<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.richie696.component</groupId>
        <artifactId>atlas-richie-component-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../atlas-richie-component-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>atlas-richie-tenant-parent</artifactId>
    <name>atlas-richie-tenant-parent</name>
    <packaging>pom</packaging>

    <modules>
        <module>atlas-richie-tenant-common</module>
        <module>atlas-richie-tenant-core</module>
        <module>atlas-richie-tenant-gateway</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.richie696.component</groupId>
                <artifactId>atlas-richie-tenant-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.richie696.component</groupId>
                <artifactId>atlas-richie-tenant-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.richie696.component</groupId>
                <artifactId>atlas-richie-tenant-gateway</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
