dynamictp:
    # 是否开启动态线程池，默认true
    enabled: true
    # 是否开启banner，默认true
    enabled-banner: false
    # 是否开启监控指标采集，默认false
    enabled-collect: true
    # 监控数据采集器类型（logging | micrometer | internal_logging），默认micrometer
    collector-types: micrometer,logging
    # 指标日志存储路径，仅用于“日志记录”类型。
    log-path: /app/logs/platform/dtp
    # 监控时间间隔（报警判断、指标采集），默认5s
    monitor-interval: 5
    # 通知平台需要配合 dynamic-tp-spring-boot-starter-extension-xxx 模块使用，
    # 参考：https://central.sonatype.com/search?q=dynamic-tp-spring-boot-starter-extension
    platforms:
        -   platform: wechat
            platform-id: 1                            # 平台id
            url-key: 3a700-127-4bd-a798-c53d8b69c     # 替换
            receivers: "test1,test2"                   # 接受人企微名称
        -   platform: ding
            # 平台id
            platform-id: 2
            # 企业钉钉url-key
            url-key: f80dad441fcd655438f4a08dcd6a
            # 替换，非sign模式可以没有此值
            secret: SECb5441fa6f375d5b9d21
            # 钉钉账号手机号
            receivers: "18888888888"
        -   platform: lark
            platform-id: 3
            url-key: 0d944ae7-b24a-40
            # 接受人飞书名称/openid
            receivers: "test1,test2"
        -   platform: email
            platformId: 4
            receivers: "richie696@vip.qq.com"
    # okhttp3 线程池配置
    okhttp3-tp:
        -   thread-pool-name: okHttpTp
            core-pool-size: 10
            maximum-pool-size: 200
            keep-alive-time: 60
    # tomcat webserver 线程池配置
    undertow-tp:
        thread-pool-name: tomcatTp
        core-pool-size: 10
        maximum-pool-size: 200
        keep-alive-time: 60
    executors:
        # 线程池名称
        -   thread-pool-name: demoExecutor
            # 线程池简化别名，用于发送通知时（当线程池名称较长时，可通过本参数精简名称，并用于发送通知）
            thread-pool-alias-name: demoExecutor
            # 核心线程池大小（默认：1）
            core-pool-size: 1
            # 最大线程池大小（默认：处理器可用核心数）
            maximum-pool-size: 8
            # 线程池空闲线程存活时间（默认：60）
            # 注：当线程数大于内核数时，这是多余的空闲线程在终止之前等待新任务的最长时间。
            keep-alive-time: 60
            # 线程池空闲线程存活时间单位（默认：SECONDS）
            unit: SECONDS
            # 是否开启报警（默认：true）
            notify-enabled: true
            # 绑定的报警平台ID（需要配合platforms节点配置）
            platform-ids:
                - 1
                - 4
            # 报警项列表
            notify-items:
                # 是否启用
                -   enabled: true
                    platform-ids:
                        - ??
                    # 报警项类型（变动通知、活跃性阈值通知、容量阈值通知、队列拒绝通知、任务运行超时警报通知、任务队列等待超时警报通知）
                    #（参考：org.dromara.dynamictp.common.em.NotifyItemEnum）
                    type: capacity
                    # 报警阈值（当type=CAPACITY时，为线程池使用率阈值；当type=RUN_TIMEOUT时，为任务执行超时阈值；当type=QUEUE_TIMEOUT时，为任务在队列等待超时阈值）
                    threshold: 0
                    # 报警间隔（单位：秒，默认：120）
                    silence-period: 120
                    # 群集通知限制（默认：1）
                    cluster-limit: 1
                # 线程池类型（参考：org.dromara.dynamictp.core.support.ExecutorType）
            executor-type: common
            # 线程池队列类型（参考：org.dromara.dynamictp.common.em.QueueTypeEnum，默认：VariableLinkedBlockingQueue）
            queue-type: VariableLinkedBlockingQueue
            # 线程池队列容量（默认：1024）
            queueCapacity: 1024
            # 是否使用公平策略（当queue-type=SYNCHRONOUS_QUEUE时，默认：非公平策略）
            fair: false
            # MemorySafeLBQ 的最大可用内存（单位：MB，默认：16）
            max-free-memory: 16
            # 当队列满了之后，拒绝策略（参考：org.dromara.dynamictp.common.em.RejectedTypeEnum，默认：AbortPolicy）
            rejected-handler-type: AbortPolicy
            # 是否允许核心线程池超时（默认：false）
            allow-core-thread-time-out: false
            # 线程名称前缀（默认：dtp）
            thread-name-prefix: dtp
            # 是否在服务停止时，等待任务执行完成后再停止服务（默认：false）
            wait-for-tasks-to-complete-on-shutdown: false
            # 线程池关闭时，等待任务完成的超时时间（单位：秒，默认：0）
            await-termination-seconds: 0
            # 是否预热所有核心线程（默认：false）
            pre-start-all-core-threads: false
            # 是否增强拒绝策略（默认：true）
            reject-enhanced: true
            # 任务执行超时阈值（仅用于统计）（单位：毫秒，默认：0）
            run-timeout: 0
            # 任务在队列等待超时阈值（仅用于统计）（单位：毫秒，默认：0）
            queue-timeout: 0
            # 任务包装器名称（默认：空）
            task-wrapper-names:
                - ??

